# Generated by Django 3.2.12 on 2022-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_two',
            field=models.IntegerField(default=0),
        ),
    ]
